// Burger Builder
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

// Order Checkout
export const PUCRHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";

// For Loading Component
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";

// Redirect when purchased
export const PURCHASE_INIT = "PURCHASE_INIT";

// Fetching Orders
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAILED = "FETCH_ORDER_FAILED";
export const FETCH_ORDER_START = "FETCH_ORDER_START";

// Authentications
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_CLEAR_TOKENS = "AUTH_CLEAR_TOKENS";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

// Redux Saga way
export const AUTH_USER = "AUTH_USER";
export const AUTH_INIT_CLEARTOKENS = "AUTH_INIT_CLEARTOKENS";
export const AUTH_INIT_LOGOUT = "AUTH_INIT_LOGOUT";
export const AUTH_CHECK_STATE = "AUTH_CHECK_STATE";
